apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-test
  annotations:
    kubernetes.io/change-cause: "acutalizacion"
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchlabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    specs:
      containers:
      - name: nginx
        image: nginx:alpline
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-test
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80